version: '2'
services:
    mysql:
        image: mysql:5.7
        ports:
            - '${MYSQL_EXTERNAL_PORT}:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
          - ./db:/var/lib/mysql
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - mysql
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
            JWT_PASSPHRASE: ${JWT_PASSPHRASE}
            CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
            DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}'
    nginx:
        build: nginx
        ports:
            - '80:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx